### ISSUE TITLE
The billing adapater is an implementation detail

### ISSUE THREAD

**Issue by rjschwei** [SUSE-Enceladus/marketplace-docs#26]
For the PAYG listing the billing-dapater is an implementation detail tha th customer doesn't need to know about. As such wording as submitted in #14 "The Azure marketplace PAYG offer is tied to a billing adapter AND Neuvector version." is providing information the customer doesn't really know what to do with. Form the customer perspective we provide 1 offer, that is NeuVector PAYG. The billing adapter is part of that offer. NeuVector is a product composed of a number of containers and the billing adapater, in the PAYG offer is part of NeuVector, we do not describe the ui controller, the scanners etc. as separate parts either.

If we feel the need to explain why a special update process is needed then let's explain it without picking appart the application layer.

**Comment by jeremy-moffitt** [comment]
@yarunachalam I don't have the ability to assign issues in this project, but I believe this is something you can cover in your next doc update... thanks!

**Comment by bear454** [comment]
Is this resolved?

**Comment by yarunachalam** [comment]
it is resolved
